
# This file controls the AWS CodeBuild

version: 2.0
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered build phase"
      - mvn clean prepare-package war:exploded
  post_build:
    commands:
      - echo "Entered the post-build phase"
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*